### ISSUE TITLE
Outdated README on `v0.1.0`

### ISSUE THREAD

**Issue by nicmr** [vectorgameexperts/bevy-async-task#10]
The README on the `v0.1.0` tag is outdated and the contained examples do not fit the codebase of the tag. It should probably be replaced with a current version of the README. Consequently, the outdated README is also featured on crates.io, which is potentially the first impression developers get when trying out this crate.

**Comment by nuzzles** [comment]
Yes, I did docs refactoring after releasing 0.1.0.

I just pushed a new release: 0.1.1

v0.1.1 and the latest Crates release should reflect the updates.

Feel free to re-open an issue if you still have one!

**Comment by nicmr** [comment]
Thank you!
