### ISSUE TITLE
Update to Bevy 0.13

### ISSUE THREAD

**Issue by Zac8668** [vectorgameexperts/bevy-async-task#7]
Is there plans to update it to Bevy latest version?

**Comment by Zac8668** [comment]
It appears that just merging #6 is enough, didn't run it yet but cargo isn't complaining.

**Comment by nuzzles** [comment]
> Is there plans to update it to Bevy latest version?

Yes! I have been a bit busy. Will get on it.

**Comment by nuzzles** [comment]
Done! v1.4 should be on Bevy 0.13 :)

**Comment by Zac8668** [comment]
Thanks! Amazing
